# Fedora Spanish translation of python-meh.master.python-meh.
# This file is distributed under the same license as the spython-meh.master.python-meh package.
# Héctor Daniel Cabrera <h.daniel.cabrera@gmail.com>\, 2009.
#
#
msgid ""
msgstr ""
"Project-Id-Version: Fedora Spanish translation of python-meh.master.python-meh\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: \n"
"Last-Translator: Domingo Becker <domingobecker@gmail.com>\n"
"Language-Team: Fedora Spanish <fedora-trans-es@redhat.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Poedit-Language: Spanish\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "Volcando lo escrito"

#: ../src/handler.py:210
msgid "The error file has been successfully written to the disk.  The program will now exit."
msgstr "El archivo del error fue escrito en el disco de manera exitosa. Ahora el programa finalizará."

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "Volcando lo no escrito"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "Ha ocurrido un problema mientras se escribía el reporte del error."

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "No existe ninguna red disponible"

#: ../src/handler.py:220
msgid "Cannot save a bug report since there is no active network device available."
msgstr "No es posible guardar un reporte del error ya que no existe disponible ningún dispositivo de red."

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating with bugzilla:\n"
"\n"
"%s"
msgstr ""
"Su error no pudo ser enviado debido al siguiente inconveniente durante el proceso de comunicación con bugzilla:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"Su error no pudo ser enviado debido a una mala información en alguno de los campos que lo describen. Seguramente esto es debido a un inconveniente del programa de envío de errores:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "No se ha posido enviar el error"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "Informe de errores no soportado"

#: ../src/savers.py:48
msgid "Your distribution does not provide a supported bug filing system, so you cannot save your exception this way."
msgstr "Su distribución no posee soporte para un sistema de archivo de errores, de modo que su excepción no puede ser almacenada de esta manera."

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "Información de error no válida"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr "Por favor, indique un nombre de usuario válido, una contraseña, y una breve descripción del error."

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "No es posible registrarse"

#: ../src/savers.py:63
#, python-format
msgid "There was an error logging into %s using the provided username and password."
msgstr "Hubo un error al registrarse en %s utilizando el nombre de usuario y la contraseña provistos."

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "El error ha sido creado"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add additional information such as what you were doing when you encountered the bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"Un nuevo error ha sido creado con su descripción adjunta. Por favor, agregue información adicional, como ser por ejemplo, qué es lo que estaba realizando cuando se encontró con este error, capturas de pantalla, o cualquier cosa que considere pertinente al error en cuestión:\n"
"\n"
"%s/%s "

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "Error actualizado"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to the CC list and your traceback added as a comment.  Please add additional descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"Ya existe un error con su información. Su cuenta ha sido añadida a la lista CC y su descripción ha sido adjuntada en forma de comentario. Por favor, agregue información descriptiva adicional al siguiente error:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "_Depuración"

#: ../src/ui/gui.py:87
#: ../src/ui/gui.py:152
msgid "_Exit"
msgstr "_Salir"

#: ../src/ui/gui.py:92
msgid "An unhandled exception has occurred.  This is most likely a bug.  Please save a copy of the detailed exception and file a bug report."
msgstr "Ha ocurrido una excepción no manipulada . Seguramente esto sea un error. Por favor, guarde una copia del detalle de la excepción y envíe un reporte de error."

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "Información"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "_Detalles"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "_Descripción del error"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "Archivo de destino"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"Almacenamiento local\n"
"Bugzilla\n"
"Servidor remoto (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "Por favor elija un destino donde almacenar la descripción de su error."

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "Guardar"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "Elegir un archivo"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "_Equipo (nombre:puerto)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "_Contraseña"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "Nombre de _usuario"

